### ISSUE TITLE
Confusing use of NuPRISM/master and NuPRISM/develop branch

### ISSUE THREAD

**Issue by tfeusels** [nuPRISM/WCSim#27] opened 2017-02-15 03:24 UTC
It would help if the difference between the branches NuPRISM/master and NuPRISM/develop is documented in the GitHub/Wiki. 
They are quite different according to https://github.com/nuPRISM/WCSim/compare/nuPRISM/master...nuPRISM:nuPRISM/develop
while both had recent pull requests being merged into them.
NuPRISM/develop seems more up-to-date with WCSim/develop (the very latest status of the code) but it's not clear to which WCSim/develop, while NuPRISM/master had more recent commits.

For pushing branches, which one should we use as reference? 
I'm assuming the following:
- WCSim/develop is most recent, and NuPRISM/develop tries to keep up with that, with the NuPRISM specific features/branches merged on top of that.
- my branches try to be up to date with WCSim/develop, so then should be merged with NuPRISM/develop (or branch off from that one) if they're also up to date with WCSim/develop. 
- unclear what NuPRISM/master does.

Any suggestions on the workflow, also documented for the future in the Wiki are welcome.

**Comment by mscott201** [comment] 2017-02-15 03:38
Yes - this should be documented (along with many other things).

NuPRISM/master is the official release branch for NuPRISM - this is what we use for the MC generation

NuPRISM/develop is the development version of the NuPRISM simulation.  This is where people should develop new code.  It will usually be more up-to-date with WCSim developments, since whenever WCSim/master is tagged I try and incorporate those changes here.  This branch does not track WCSim/develop.

If you have branched off WCSim/develop then this is slightly tricky to incorporate directly into the NuPRISM branches, since it does not correspond to a tagged version of WCSim.

The original workflow was supposed to be that NuPRISM development branched off NuPRISM/develop, and was then pulled into NuPRISM/master whenever we freeze.  WCSim development should branch off WCSim/develop and then pull into WCSim/master.  When there is a WCSim freeze the new WCSim code is incorporated into NuPRISM/develop, then into NuPRISM/master for the next freeze.

The mPMT code was intended to merge in to WCSim, so branched from WCSim/develop.  We now want to incorporate it into NuPRISM/develop, but not (yet) into WCSim/develop, going against the original workflow.

I am going to create a new mPMT branch for your code, which will avoid this issue.  You can then merge the NuPRISM/master branch into this new branch to pick up the NuPRISM changes we need.  If this new branch gets merged with a tagged version of WCSim in the future we can then combine it gracefully with the main NuPRISM/master and NuPRISM/develop branches.

**Comment by tfeusels** [comment] 2017-02-24 01:36
@mscott201 I am now very confused by the nuPRISM/mPMT branch. I expected a lot of conflicts but merging in my very latest mPMT branch went too smooth. From the network graph it looks like the nuPRISM/mPMT branch does not branch of either current nuPRISM/develop nor  nuPRISM/master but from a nuPRISM/develop from end of July. Can you elaborate on what this mPMT branch actually is?

**Comment by tfeusels** [comment] 2017-02-24 01:41
Just to clarify: nuPRISM/mPMT branches off the develop branch (from WCSim) dated end of July.
My local WCSim-mPMT branch merged with latest WCSim/develop up to Feb 20.This one I now merged into nuPRISM/mPMT.
 After that I will not update the nuPRISM/mPMT branch with newer WCSim/develop anymore (pending big changes for G4.10 coming). 
Now I need to merge nuPRISM/develop in nuPRISM/mPMT and resolve remaining conflicts.

**Comment by mscott201** [comment] 2017-02-24 02:58
Hi Tom,

Yes, I branched off WCSim/develop to make it easier for you.   If you merge in nuPRISM/develop then we should be able to use this branch for reconstruction studies.

I'm expecting a freeze of WCSim in the next month, so once that happens we should merge this branch with the frozen WCSim, then merge it into nuPRISM/master.  We could also leave it as a side branch, but we should update the nuPRISM/WCSim code to use the newer version of G4 and improved electronics simulation.

**Comment by mscott201** [comment] 2017-05-11 19:20
Issue resolved and detailed in Wiki

**Closed as completed by mscott201** 2017-05-11 19:20 UTC
